### ISSUE TITLE
Krb5.conf

### ISSUE THREAD

**Issue by RogerGMartins** [jacobludriks/node-krbclient#1]
hey there,

I need to use a different default_tkt_enctypes/default_tgs_enctypes configuration to get the ticket data.
I'm still very fresh with node and bindings for node, so i'm having an hard time understanding whats happening.

Can you route me to the correct direction if you have knowledge of this?
I tried to setup the KRB5_CONFIG env variable with no success.
I added a KRB5.ini with the configuration in the expected path (C:\Windows\krb5.ini) with no success as well.

I guess i will have to change the configuration programaticly with the gssapi, so i'm starting the research with that.

Thanks in advance.

**Comment by jacobludriks** [comment]
nope
